[package]
name = "rlox_basic"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
signal-hook = "0.3"  # Use the latest version available

[profile.dev]







